name: socialbuddybot
description: Social Buddy Bot App
version: 2.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 2.0.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.8.0
  collection: ^1.15.0
  device_calendar: ^3.1.0
  firebase_ml_vision: ^0.11.0
  flare_flutter: ^2.0.6
  flutter_svg: ^0.19.3
  flutter_tts_improved: ^1.0.3
  font_awesome_flutter: ^8.12.0
  get_it: ^6.0.0
  package_info: ^2.0.0
  rxdart: ^0.26.0
  state_persistence: ^0.1.0
  time: ^2.0.0
  validators: ^2.0.1

dev_dependencies:
  build_runner: ^1.8.1
  flutter_launcher_icons: ^0.7.4
  import_sorter: ^4.2.1
  json_serializable: ^3.3.0
  pedantic:

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/flare/

import_sorter:
  emojis: false
  comments: false
  ignored_files: # Optional, defaults to []
    - lib/env\.dart
    - (?:(?!/)(?:.|\n))*/(?:(?!\.g\.dart)(?:.|\n))*\.g\.dart
    - (?:(?!/)(?:.|\n))*/(?:(?!\.freezed\.dart)(?:.|\n))*\.freezed\.dart
